# Logistic Regression

In [23]:
import numpy as np
import pandas as pd 
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, classification_report
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 200)
pd.options.display.max_colwidth=300

import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams["patch.force_edgecolor"] = True

import seaborn as sns

In [3]:
df = pd.read_csv('application_clean.csv')

In [4]:
df.head()

Unnamed: 0  sk_id_curr  target  flag_own_car  flag_own_realty  \
0           0      100002       1             0                1   
1           1      100003       0             0                0   
2           2      100004       0             1                1   
3           3      100006       0             0                1   
4           4      100007       0             0                1   

   cnt_children  amt_income_total  amt_credit  amt_annuity  amt_goods_price  \
0             0          202500.0    406597.5      24700.5         351000.0   
1             0          270000.0   1293502.5      35698.5        1129500.0   
2             0           67500.0    135000.0       6750.0         135000.0   
3             0          135000.0    312682.5      29686.5         297000.0   
4             0          121500.0    513000.0      21865.5         513000.0   

   region_population_relative  days_birth  days_employed  days_registration  \
0                    0.018801       -9461         -637.0            -3648.0   
1                    0.003541      -16765        -1188.0            -1186.0   
2                    0.010032      -19046         -225.0            -4260.0   
3                    0.008019      -19005        -3039.0            -9833.0   
4                    0.028663      -19932        -3038.0            -4311.0   

   days_id_publish  own_car_age  flag_mobil  flag_emp_phone  flag_work_phone  \
0            -2120          NaN           1               1                0   
1             -291          NaN           1               1                0   
2            -2531         26.0           1               1                1   
3            -2437          NaN           1               1                0   
4            -3458          NaN           1               1                0   

   flag_cont_mobile  flag_phone  flag_email  cnt_fam_members  \
0                 1           1           0              1.0   
1                 1           1           0              2.0   
2                 1           1           0              1.0   
3                 1           0           0              2.0   
4                 1           0           0              1.0   

   region_rating_client  region_rating_client_w_city  hour_appr_process_start  \
0                     2                            2                       10   
1                     1                            1                       11   
2                     2                            2                        9   
3                     2                            2                       17   
4                     2                            2                       11   

   reg_region_not_live_region  reg_region_not_work_region  \
0                           0                           0   
1                           0                           0   
2                           0                           0   
3                           0                           0   
4                           0                           0   

   live_region_not_work_region  reg_city_not_live_city  \
0                            0                       0   
1                            0                       0   
2                            0                       0   
3                            0                       0   
4                            0                       0   

   reg_city_not_work_city  live_city_not_work_city  ext_source_1  \
0                       0                        0      0.083037   
1                       0                        0      0.311267   
2                       0                        0           NaN   
3                       0                        0           NaN   
4                       1                        1           NaN   

   ext_source_2  ext_source_3  apartments_avg  basementarea_avg  \
0      0.262949      0.139376          0.0247            0.0369   
1      0.622246           NaN   

In [5]:
X = df.iloc[:,3:]
y = df.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=5)

In [6]:
from sklearn.preprocessing import MinMaxScaler, Imputer
imputer = Imputer(strategy = 'median')
scaler = MinMaxScaler(feature_range = (0, 1))
imputer.fit(X_train)

X_train = imputer.transform(X_train)
X_test = imputer.transform(X_test)
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

/Users/geschew/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [18]:
from sklearn.linear_model import LogisticRegression
logit = LogisticRegression(C = 0.0001, class_weight='balanced')
logit.fit(X_train, y_train)

/Users/geschew/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=0.0001, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
y_pred_logp = logit.predict_proba(X_test)[:, 1]
y_pred_logp

array([0.47463077, 0.50618663, 0.46571727, ..., 0.34349089, 0.29472742,
       0.494976  ])

In [20]:
y_pred_log = logit.predict(X_test)
y_pred_log

array([0, 1, 0, ..., 0, 0, 0])

In [21]:
confusion_matrix(y_test, y_pred_log)

array([[46124, 24680],
       [ 2018,  4056]])

In [24]:
print( accuracy_score(y_test, y_pred_log) )

0.652722495382294


In [25]:
print(classification_report(y_test, y_pred_log))

              precision    recall  f1-score   support

           0       0.96      0.65      0.78     70804
           1       0.14      0.67      0.23      6074

    accuracy                           0.65     76878
   macro avg       0.55      0.66      0.50     76878
weighted avg       0.89      0.65      0.73     76878

